version: '3'

services:
  jitsi-keycloak:
    image: testkey
    container_name: jisi-keycloak
    restart: unless-stopped
    environment:
      JITSI_SECRET: 123456789
      DEFAULT_ROOM: meeting
      INVITE_ROOM_PREFIX: invite
      JITSI_URL: https://meet.example.com/
      JITSI_SUB: meet.example.com
    volumes:
    - ./config:/config
    ports:
    - 3000:3000
